#!/usr/bin/env bash
# Regenerates manifest.md from the files tracked by git.
# Run from anywhere inside the kit repository after adding, renaming or
# deleting kit files.
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

{
  echo "# Manifest"
  echo
  echo "<!-- Generated by scripts/update-manifest.sh — do not edit by hand. -->"
  echo
  # LC_ALL=C makes the sort order deterministic across platforms/locales.
  git ls-files | LC_ALL=C sort | while IFS= read -r f; do
    echo "- \`$f\`"
  done
} > manifest.md

echo "manifest.md regenerated ($(git ls-files | wc -l | tr -d ' ') files)."
